services:
  mwmbl-crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    image: mwmbl/crawler
    container_name: mwmbl-crawler
    pull_policy: always
    depends_on:
      - redis
    environment:
      # Add your API key here:
      # - MWMBL_API_KEY=

      # REQUIRED: Contact info for website administrators
      - MWMBL_CONTACT_INFO=CHANGE_ME@example.com

      # Set value of ./mwmbl/crawler/env_vars.py
      - CRAWLER_WORKERS=2
      - CRAWLER_THREADS=20
      - CRAWL_DELAY_SECONDS=0.0

      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    volumes:
      - crawler_data:/root/.mwmbl

    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    # CPU restrictions if needed:
    #     resources:
    #       limits:
    #         cpus: '0.50'

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  redis_data:
  crawler_data:
